### ISSUE TITLE
zscoreweighted?

### ISSUE THREAD

**Issue by barnabe** [charlesmalafosse/custom-factor-model#1]
in your zscore iteration you have a line with a zscoreweighted call which does not seem to correspond to anything else

`zscores_new_values <- zscoreweighted(zscores_values, factor_data$wgt, 3, -3)`

the code stops there. typo?

**Comment by CharlesMalafosse1275** [comment]
Hi Barnabe,
This is a call to the function defined earlier in the file.

`
################################################################################################################
#  Z-SCORE CALCULATION FUNCTION - FOR WEIGHTED MEAN OF 0 AND STDEV OF 1
################################################################################################################
zscoreweighted <- function (x, wgt, UpperBoundWinsorized, LowerBoundWinsorized) {
  ## Returns z-scored values
  x[x == 0] <- NA # Exposure kept to zero.
  x.mean <- weighted.mean(x,wgt,na.rm=TRUE)
  x.sd <- sd(x,na.rm=TRUE)
  x.z <- (x-x.mean) /x.sd
  x.z <- sapply(x.z, min, UpperBoundWinsorized)
  x.z <- sapply(x.z, max, LowerBoundWinsorized)
  x[is.na(x)] <- 0
  return(x.z)
}
`

Please let me know if that's answer your point.
Thanks
Charles

**Comment by barnabe** [comment]
Thank you for a quick answer. Yes of course. somehow I did not see it and CTRL-F didn't help me ...
